Add zig language run support
formulahendry/vscode-code-runner pull request #959
Opened 2022-07-13 20:25 UTC by forinda

2022-07-14 05:24 UTC, formulahendry commented on README.md
> -Run code snippet or code file for multiple languages: **C, C++, Java, JavaScript, PHP, Python, Perl, Perl 6, Ruby, Go, Lua, Groovy, PowerShell, BAT/CMD, BASH/SH, F# Script, F# (.NET Core), C# Script,
Just append to the end.

2022-07-14 05:25 UTC, formulahendry commented on package.json
> -  "description": "Run C, C++, Java, JS, PHP, Python, Perl, Ruby, Go, Lua, Groovy, PowerShell, CMD, BASH, F#, C#, VBScript, TypeScript, CoffeeScript, Scala, Swift, Julia, Crystal, OCaml, R, AppleScrip
Same here: Just append to the end.

2022-07-14 05:26 UTC, formulahendry commented on package.json
> +            "zig": "zig run $fileName",
No `$fileName` needed

2022-07-14 05:27 UTC, formulahendry commented on package.json
> +            ".zig": "zig run $fileName",
Same here: No `$fileName` needed

2022-07-14 05:28 UTC, formulahendry requested changes
Others look good to me~

2022-07-14 05:39 UTC, forinda commented
Let me rework on it

2022-07-14 05:49 UTC, forinda commented on package.json
> -  "description": "Run C, C++, Java, JS, PHP, Python, Perl, Ruby, Go, Lua, Groovy, PowerShell, CMD, BASH, F#, C#, VBScript, TypeScript, CoffeeScript, Scala, Swift, Julia, Crystal, OCaml, R, AppleScrip
Ok

2022-07-14 05:58 UTC, forinda commented on package.json
> +            ".zig": "zig run $fileName",
Resolved the `$fileName`

2022-07-14 05:59 UTC, forinda commented on package.json
> +            "zig": "zig run $fileName",
Removed the `$fileName`

2022-07-14 08:12 UTC, formulahendry commented on package.json
> -  "description": "Run C, C++, Java, JS, PHP, Python, Perl, Ruby, Go, Lua, Groovy, PowerShell, CMD, BASH, F#, C#, VBScript, TypeScript, CoffeeScript, Scala, Swift, Julia, Crystal, OCaml, R, AppleScrip
Please also update this one as well, 😃

2022-07-14 08:12 UTC, formulahendry requested changes
Just leave one comment~

2022-07-14 08:39 UTC, forinda commented
> Just leave one comment~

Done

2022-07-14 10:36 UTC, formulahendry requested changes
I still not see the updates:
![image](https://user-images.githubusercontent.com/1050213/178963555-1d0deccd-5fa3-4246-8fc2-9294b049b99c.png)

BTW, `zig` should be `Zig`?

2022-07-14 10:42 UTC, forinda commented
> I still not see the updates:
> ![image](https://user-images.githubusercontent.com/1050213/178963555-1d0deccd-5fa3-4246-8fc2-9294b049b99c.png)
> 
> BTW, `zig` should be `Zig`?

 In the latest commit do you mean zig in the readme to be capitalized

2022-07-14 11:29 UTC, forinda reviewed
Capitalize zig

2022-07-17 03:12 UTC, formulahendry commented
> > I still not see the updates:
> > ![image](https://user-images.githubusercontent.com/1050213/178963555-1d0deccd-5fa3-4246-8fc2-9294b049b99c.png)
> > BTW, `zig` should be `Zig`?
> 
> In the latest commit do you mean zig in the readme to be capitalized

@forinda I mean this line: https://github.com/forinda/vscode-code-runner/blob/5c5534480c8576d56613007e224a6ee1a665e7e9/package.json#L4_

2022-07-17 07:20 UTC, forinda commented
> > > I still not see the updates:
> > > ![image](https://user-images.githubusercontent.com/1050213/178963555-1d0deccd-5fa3-4246-8fc2-9294b049b99c.png)
> > > BTW, `zig` should be `Zig`?
> > 
> > 
> > In the latest commit do you mean zig in the readme to be capitalized
> 
> @forinda I mean this line: https://github.com/forinda/vscode-code-runner/blob/5c5534480c8576d56613007e224a6ee1a665e7e9/package.json#L4_

Updated

2022-07-17 09:04 UTC, formulahendry approved these changes

2022-07-17 09:06 UTC, merged